process_raw:
  method: sep
  ellipse_scale: 2.0
  preview:
  preview_raw:
  dump_jpg:
  dump_raw_jpg:
  sextractor_path:
  simple_detection:
    gaussian_sigma: 1.2
    percentile_threshold: 99.8
    sigma_threshold: 5.0
    opening_size: 2
    min_pixels: 2
  sep:
    threshold_sigma: 5.0
    minarea: 32
    deblend_nthresh: 32
    deblend_cont: 0.9
    clean: true
    clean_param: 1.0
    bw: 64
    bh: 64
    fw: 3
    fh: 3
  sewpy:
    params:
      - X_IMAGE
      - Y_IMAGE
      - FLUX_ISO
      - FLUX_MAX
      - BACKGROUND
      - A_IMAGE
      - B_IMAGE
      - THETA_IMAGE
      - FLAGS
    config:
      DETECT_MINAREA: 3
      DETECT_THRESH: 5.0
      ANALYSIS_THRESH: 5.0
      FILTER: Y
      DEBLEND_NTHRESH: 32
      DEBLEND_MINCONT: 0.005

psf:
  halfwidth: 50
  zoom_halfwidth: 20
  contour_levels: 6
  max_match_radius: 50.0
  pix2mm:
  annotate_psf: false
  single_contour_2rms: false
  use_catalog_shape: false
  vmin:
  vmax:
